spring:
  cloud:
    compatibility-verifier:
      enabled=false:
  application:
        name: mock
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka